[package]
name = "invoker-game-wasm"
version = "0.1.0-SNAPSHOT"
authors = ["zerosum <info@zerosum.dev>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
invoker-game-core = { path = "../core" }
