name: publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 14.x
    
    - run: |
        wasm-pack build ./wasm
        cd ./site
        npm install
        npm run build
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/build
